version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - laravel

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      APP_ENV: production
      LIGHTHOUSE_CACHE_ENABLE: 'false'
    ports:
      - 8000:8000
    networks:
      - laravel
    restart: always
    command: >
      bash -c "php artisan lighthouse:clear-cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/graphql
    restart: always
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data: {}
