import './globals.css';
import { Inter } from 'next/font/google';
import { Provider } from '@/components/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center items-center min-h-screen bg-gray-100">
          <div className="w-[95vw]">
            <h1 className="text-4xl text-center mb-10">Memo Test Game</h1>
            <Provider>
              <main>{children}</main>
            </Provider>
          </div>
        </div>
      </body>
    </html>
  );
}
